name: Documentation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # https://github.com/bevyengine/bevy/issues/850#issuecomment-758341779
    - run: |
        sudo apt install -y pulseaudio
        sudo adduser $(id -u -n) pulse-access
        sudo rm -rf /var/run/pulse /var/lib/pulse /root/.config/pulse
        sudo pulseaudio -D --verbose --exit-idle-time=-1 --system --disallow-exit
    - name: Run tests
      run: cargo test --verbose

  doc:
    runs-on: ubuntu-latest
    needs: test
    if:  github.event_name == 'push' || github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v2
    - name: Run doc
      run: cargo doc --no-deps

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc/